### ISSUE TITLE
The add-on does not work correctly in Blender 5.0.

### ISSUE THREAD

**Issue by RonmeSP** [Dangry98/modifier_list-for-Blender-4.0#62]
The add-on does not work correctly with the subdivision modifier.

Python: Traceback (most recent call last):
  File "C:\Users\RonmeSP\AppData\Roaming\Blender Foundation\Blender\5.0\extensions\blender_org\Modifier_List_Fork\modules\ui\properties_editor.py", line 31, in draw
    modifiers_ui_with_list(context, layout, new_menu=False)
  File "C:\Users\RonmeSP\AppData\Roaming\Blender Foundation\Blender\5.0\extensions\blender_org\Modifier_List_Fork\modules\ui\modifiers_ui.py", line 1298, in modifiers_ui_with_list
    getattr(mp, active_mod.type)(col, ob, active_mod)
  File "C:\Users\RonmeSP\AppData\Roaming\Blender Foundation\Blender\5.0\extensions\blender_org\Modifier_List_Fork\modules\ui\properties_data_modifier.py", line 1219, in SUBSURF
    and scene.cycles.feature_set == 'EXPERIMENTAL' and md.use_limit_surface
        ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CyclesRenderSettings' object has no attribute 'feature_set'

**Comment by Dangry98** [comment]
Hi, thanks for the report, the issue has been fixed in Modifier List 2.0
https://extensions.blender.org/add-ons/modifier-list-fork/

Closing issue :)
